## noresetcounter.conf - minimal configuration for postgres counter
# Query used by sqlcounter noresetcounter
query = "SELECT SUM(AcctSessionTime) FROM radacct WHERE UserName='%{User-Name}' AND EXTRACT(epoch FROM AcctStartTime) + AcctSessionTime > '%%b'"
